kind: Secret
apiVersion: v1
metadata:
  name: buildconfig-source-secret
stringData:
  ssh-privatekey: >-
    <your private ssh key>
type: kubernetes.io/ssh-auth

# oc create secret generic buildconfig-source-secret \
#    -n backstage-dev \
#    --from-file=ssh-privatekey=<path/to/ssh/private/key> \
#    --type=kubernetes.io/ssh-auth
