kind: Deployment
apiVersion: apps/v1
metadata:
  name: backstage
spec:
  template:
    spec:
      containers:
        - name: backstage
          command: ["/bin/sh", "-c", "NODE_TLS_REJECT_UNAUTHORIZED=0 node packages/backend --config app-config.yaml"]