kind: Deployment
apiVersion: apps/v1
metadata:
  name: backstage
spec:
  template:
    spec:
      containers:
        - name: backstage
          image: image-registry.openshift-image-registry.svc:5000/backstage-dev/backstage:latest