kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: backstage
  labels:
    deployment: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem