kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: backstage-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
