apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: Opaque
data:
  POSTGRESQL_ADMIN_PASSWORD: aHVudGVy
  POSTGRESQL_DATABASE: YmFja3N0YWdl
  POSTGRESQL_PASSWORD: aHVudGVy
  POSTGRESQL_USER: YmFja3N0YWdl
