kind: Service
apiVersion: v1
metadata:
  name: backstage
  namespace: backstage
  uid: d4c3377d-dfb7-466f-a8bc-c6af368dc4d9
  resourceVersion: '442217'
  creationTimestamp: '2022-11-22T00:40:07Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"backstage","namespace":"backstage"},"spec":{"ports":[{"name":"backstage","port":80,"targetport":3000}],"selector":{"app":"backstage"}}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2022-11-22T00:48:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-11-22T01:25:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":80,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  ports:
    - name: backstage
      protocol: TCP
      port: 7007
      targetPort: http
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: backstage