kind: ConfigMap
apiVersion: v1
metadata:
  name: backstage-cm
  namespace: backstage
data:
  BACKSTAGE_SUB_DOMAIN: backstage-backstage
  OPENSHIFT_BASE_DOMAIN: itzroks-671000wmfn-8vdu9o-6ccd7f378ae819553d37d5f2ee142bd6-0000.au-syd.containers.appdomain.cloud
  AUTH_SESSION_SECRET: devsessionsecret
  AUTH_IBM_VERIFY_META_URL: https://ryu.verify.ibm.com/oidc/endpoint/default/.well-known/openid-configuration
  AUTH_IBM_VERIFY_CLIENT_ID: 39662a44-8e00-4292-88a6-e9952c6fdbe4
  AUTH_IBM_VERIFY_CLIENT_SECRET: v4sbSAAtGC
  KUBE_API_ENDPOINT: https://c100-e.au-syd.containers.cloud.ibm.com:30783
  KUBE_CLUSTER_NAME: local-cluster
  KUBE_SERVICE_ACCOUNT_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6IkoyelNPN3NaOEppRjg2dEpHMmVzem1iU1hRNFdVUDlxZU40UWJzczV1LWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJiYWNrc3RhZ2UiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYmFja3N0YWdlLXRva2VuLWs0cXd2Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImJhY2tzdGFnZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjI0YTI0ZmIwLTBkNTAtNGVhZC1hNTViLTQ3YzVhMzQzZTA1ZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpiYWNrc3RhZ2U6YmFja3N0YWdlIn0.KohGLWGMaTCWQvvYMUK9VTUSWvdB-ySL7Xf4VErPTq_m_kw2vZq02X3CCl7ZP4ibyu87rCAihvLmQPWyNxrtY_ctQN78FBYi-AwaM1mrxgWhvKe45LXrTpvoMQL2GqSIiid0vO-o_cBDhhdZ9C7i1uH-6HUxoEAUDua5xmUN0v7UK290pt7vi7GpTukjunOyhgJsbpKgr0LOHqBB5iw6xLAJ_yBJ19yVALOFF15t4E-vgTWbBzdpu5LHWVf71CWfXVnuSlexLHWXhdFDuwckzfKT1lmQ747Lap_Mbnu9uHxt0zSXZHn-mHBv2zP8qp3u6xyr1my6rsyzEjRzAs-2Bg
  RHACM_HUB_CLUSTER: local-cluster
  # GITHUB_TOKEN
  # AUTH_GITHUB_CLIENT_ID
  # AUTH_GITHUB_CLIENT_SECRET