kind: Deployment
apiVersion: apps/v1
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          ports:
            - name: http
              containerPort: 7007
              protocol: TCP
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: backstage-cm
            - secretRef:
                name: postgresql-secrets
          image: image-registry.openshift-image-registry.svc:5000/backstage-dev/backstage:latest